// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExpansionRequest {
    /// Set of components needed to interpret the transform, or which
    /// may be useful for its expansion.  This includes the input
    /// PCollections (if any) to the to-be-expanded transform, along
    /// with their coders and windowing strategies.
    #[prost(message, optional, tag = "1")]
    pub components: ::core::option::Option<super::super::pipeline::v1::Components>,
    /// The actual PTransform to be expaneded according to its spec.
    /// Its input should be set, but its subtransforms and outputs
    /// should not be.
    #[prost(message, optional, tag = "2")]
    pub transform: ::core::option::Option<super::super::pipeline::v1::PTransform>,
    /// A namespace (prefix) to use for the id of any newly created
    /// components.
    #[prost(string, tag = "3")]
    pub namespace: ::prost::alloc::string::String,
    /// (Optional) Map from a local output tag to a coder id.
    /// If it is set, asks the expansion service to use the given
    /// coders for the output PCollections. Note that the request
    /// may not be fulfilled.
    #[prost(map = "string, string", tag = "4")]
    pub output_coder_requests: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// A set of requirements that must be used by the expansion service to
    /// interpret the components provided with this request.
    #[prost(string, repeated, tag = "5")]
    pub requirements: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// (Optional) A set of Pipeline Options that should be used
    /// when expanding this transform.
    #[prost(message, optional, tag = "6")]
    pub pipeline_options: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExpansionResponse {
    /// Set of components needed to execute the expanded transform,
    /// including the (original) inputs, outputs, and subtransforms.
    #[prost(message, optional, tag = "1")]
    pub components: ::core::option::Option<super::super::pipeline::v1::Components>,
    /// The expanded transform itself, with references to its outputs
    /// and subtransforms.
    #[prost(message, optional, tag = "2")]
    pub transform: ::core::option::Option<super::super::pipeline::v1::PTransform>,
    /// A set of requirements that must be appended to this pipeline's
    /// requirements.
    #[prost(string, repeated, tag = "3")]
    pub requirements: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// (Optional) An string representation of any error encountered while
    /// attempting to expand this transform.
    #[prost(string, tag = "10")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiscoverSchemaTransformRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchemaTransformConfig {
    /// Config schema of the SchemaTransform
    #[prost(message, optional, tag = "1")]
    pub config_schema: ::core::option::Option<super::super::pipeline::v1::Schema>,
    /// Names of input PCollections
    #[prost(string, repeated, tag = "2")]
    pub input_pcollection_names: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// Names of output PCollections
    #[prost(string, repeated, tag = "3")]
    pub output_pcollection_names: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// Description of this transform and usage used for documentation.
    /// May be markdown formatted.
    /// Note that configuration parameters may also have documentation attached
    /// as part of the config_schema.
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoverSchemaTransformResponse {
    /// A mapping from SchemaTransform ID to schema transform config of discovered
    /// SchemaTransforms
    #[prost(map = "string, message", tag = "1")]
    pub schema_transform_configs: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        SchemaTransformConfig,
    >,
    /// If list of identifies are empty, this may contain an error.
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod expansion_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Job Service for constructing pipelines
    #[derive(Debug, Clone)]
    pub struct ExpansionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ExpansionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ExpansionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ExpansionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ExpansionServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn expand(
            &mut self,
            request: impl tonic::IntoRequest<super::ExpansionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExpansionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/org.apache.beam.model.expansion.v1.ExpansionService/Expand",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "org.apache.beam.model.expansion.v1.ExpansionService",
                        "Expand",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// A RPC to discover already registered SchemaTransformProviders.
        /// See https://s.apache.org/easy-multi-language for more details.
        pub async fn discover_schema_transform(
            &mut self,
            request: impl tonic::IntoRequest<super::DiscoverSchemaTransformRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DiscoverSchemaTransformResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/org.apache.beam.model.expansion.v1.ExpansionService/DiscoverSchemaTransform",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "org.apache.beam.model.expansion.v1.ExpansionService",
                        "DiscoverSchemaTransform",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod expansion_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ExpansionServiceServer.
    #[async_trait]
    pub trait ExpansionService: std::marker::Send + std::marker::Sync + 'static {
        async fn expand(
            &self,
            request: tonic::Request<super::ExpansionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExpansionResponse>,
            tonic::Status,
        >;
        /// A RPC to discover already registered SchemaTransformProviders.
        /// See https://s.apache.org/easy-multi-language for more details.
        async fn discover_schema_transform(
            &self,
            request: tonic::Request<super::DiscoverSchemaTransformRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DiscoverSchemaTransformResponse>,
            tonic::Status,
        >;
    }
    /// Job Service for constructing pipelines
    #[derive(Debug)]
    pub struct ExpansionServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ExpansionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ExpansionServiceServer<T>
    where
        T: ExpansionService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/org.apache.beam.model.expansion.v1.ExpansionService/Expand" => {
                    #[allow(non_camel_case_types)]
                    struct ExpandSvc<T: ExpansionService>(pub Arc<T>);
                    impl<
                        T: ExpansionService,
                    > tonic::server::UnaryService<super::ExpansionRequest>
                    for ExpandSvc<T> {
                        type Response = super::ExpansionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExpansionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ExpansionService>::expand(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExpandSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/org.apache.beam.model.expansion.v1.ExpansionService/DiscoverSchemaTransform" => {
                    #[allow(non_camel_case_types)]
                    struct DiscoverSchemaTransformSvc<T: ExpansionService>(pub Arc<T>);
                    impl<
                        T: ExpansionService,
                    > tonic::server::UnaryService<super::DiscoverSchemaTransformRequest>
                    for DiscoverSchemaTransformSvc<T> {
                        type Response = super::DiscoverSchemaTransformResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::DiscoverSchemaTransformRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ExpansionService>::discover_schema_transform(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DiscoverSchemaTransformSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ExpansionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "org.apache.beam.model.expansion.v1.ExpansionService";
    impl<T> tonic::server::NamedService for ExpansionServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
