[package]
name = "flare-sql"
version = "0.1.0"
edition = "2024"
description = "FlareDB SQL shell"
license = "Apache-2.0"
repository = "https://github.com/flare-db/flare-db"
authors = ["Ganesh Sivakumar"]

[dependencies]
paimon-datafusion = "0.3.0"
paimon = "0.3.0"
datafusion = "=54.1.0"
dirs = "5"
rustyline = "14.0"
anyhow = "1.0.103"
