use crate::fusion::pipeline::{ConsumerMetaData, ExecutableGraph, ExecutableNode};
use beam_model_rs::v1::Components;
use petgraph::dot::{Config, Dot};
use std::{collections::HashMap, fmt};

impl fmt::Debug for ExecutableNode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.debug_label())
    }
}

pub fn executable_graph_to_dot(graph: &ExecutableGraph) -> String {
    let executable_graph = graph.get_executable_graph();
    let dot = format!(
        "{:?}",
        Dot::with_attr_getters(
            executable_graph,
            &[Config::NodeNoLabel, Config::EdgeNoLabel],
            &|_, edge| edge_attributes(edge.weight()),
            &|_, (node_index, node)| node_attributes(node_index.index(), node),
        )
    );

    dot.replacen(
        "digraph {\n",
        &format!(
            "digraph executable_graph {{\n    // Generated by petgraph::dot::Dot\n    // nodes: {}\n    // edges: {}\n    rankdir = TB\n    graph [fontname = \"Helvetica\", nodesep = 0.60, ranksep = 0.80]\n    node [fontname = \"Helvetica\", fontsize = 10]\n    edge [fontname = \"Helvetica\", fontsize = 9]\n",
            executable_graph.node_count(),
            executable_graph.edge_count(),
        ),
        1,
    )
}

fn node_attributes(node_index: usize, node: &ExecutableNode) -> String {
    format!(
        "label = <{}>, shape = plain",
        node_label_html(node_index, node),
    )
}

fn edge_attributes(metadata: &ConsumerMetaData) -> String {
    format!(
        "label = <{}>, color = \"#6b7280\", fontcolor = \"#374151\"",
        edge_label_html(metadata),
    )
}

fn node_label_html(node_index: usize, node: &ExecutableNode) -> String {
    match node {
        ExecutableNode::Worker(stage) => {
            let ordered_transforms: Vec<_> = stage.transforms().into_iter().collect();
            let components = stage.components();

            let mut output_pcols: Vec<_> = stage
                .output_pcols()
                .iter()
                .map(|pcollection| pcollection.id.clone())
                .collect();
            output_pcols.sort();

            let mut rows = vec![
                header_row(&format!("Worker Node #{}", node_index), "#bfdbfe"),
                kv_row("id", &stage.id()),
                kv_row("input", &stage.input_pcol().id),
            ];
            for (index, transform) in ordered_transforms.iter().enumerate() {
                let transform_node = transform.node();
                rows.push(flow_transform_row(index + 1, &transform_node.unique_name));
                rows.push(flow_io_row(
                    "consumes",
                    &format_pcollection_map(&transform_node.inputs, &components),
                ));
                rows.push(flow_io_row(
                    "produces",
                    &format_pcollection_map(&transform_node.outputs, &components),
                ));
            }

            rows.push(section_row(&format!("outputs ({})", output_pcols.len())));
            if output_pcols.is_empty() {
                rows.push(value_row("-"));
            } else {
                for output_pcol in output_pcols {
                    rows.push(value_row(&output_pcol));
                }
            }

            table_html("#2563eb", "#eff6ff", rows)
        }
        ExecutableNode::Runner(transform) => {
            let mut output_pcols: Vec<_> = transform.output_pcol_ids().into_iter().collect();
            output_pcols.sort();

            let mut rows = vec![
                header_row(&format!("Runner Node #{}", node_index), "#fde68a"),
                kv_row("id", &transform.id()),
                kv_row("name", &transform.unique_name()),
                section_row(&format!("outputs ({})", output_pcols.len())),
            ];

            if output_pcols.is_empty() {
                rows.push(value_row("-"));
            } else {
                for output_pcol in output_pcols {
                    rows.push(value_row(&output_pcol));
                }
            }

            table_html("#d97706", "#fffbeb", rows)
        }
    }
}

fn edge_label_html(metadata: &ConsumerMetaData) -> String {
    let component_coders = metadata
        .component_coder
        .as_ref()
        .map(|coders| {
            if coders.is_empty() {
                "-".to_string()
            } else {
                coders.join(", ")
            }
        })
        .unwrap_or_else(|| "-".to_string());

    table_html(
        "#6b7280",
        "#f9fafb",
        vec![
            header_row("PCollection edge", "#e5e7eb"),
            kv_row("producer", &metadata.producer_transform_id),
            kv_row("pcol", &metadata.produced_pcol_id),
            kv_row("coder", &metadata.coder_id),
            kv_row("components", &component_coders),
            kv_row("consumer", &metadata.consumer_transfrom_id),
        ],
    )
}

fn table_html(border_color: &str, background_color: &str, rows: Vec<String>) -> String {
    format!(
        "<TABLE BORDER=\"1\" CELLBORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"5\" COLOR=\"{}\" BGCOLOR=\"{}\">{}</TABLE>",
        border_color,
        background_color,
        rows.join(""),
    )
}

fn header_row(value: &str, background_color: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"CENTER\" BGCOLOR=\"{}\"><B>{}</B></TD></TR>",
        background_color,
        html_escape(value),
    )
}

fn section_row(value: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"LEFT\"><B>{}</B></TD></TR>",
        html_escape(value),
    )
}

fn kv_row(key: &str, value: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"LEFT\"><B>{}:</B> {}</TD></TR>",
        html_escape(key),
        wrap_html(value, 64),
    )
}

fn flow_transform_row(index: usize, value: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"LEFT\" BGCOLOR=\"#dbeafe\"><B>{}. {}</B></TD></TR>",
        index,
        wrap_html(value, 72),
    )
}

fn flow_io_row(key: &str, value: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"LEFT\"><I>{}:</I> {}</TD></TR>",
        html_escape(key),
        wrap_html(value, 84),
    )
}

fn value_row(value: &str) -> String {
    format!("<TR><TD ALIGN=\"LEFT\">{}</TD></TR>", wrap_html(value, 72),)
}

fn format_pcollection_map(values: &HashMap<String, String>, components: &Components) -> String {
    if values.is_empty() {
        return "-".to_string();
    }

    let mut entries: Vec<_> = values
        .iter()
        .map(|(tag, pcollection)| {
            format!(
                "{}: {} ({})",
                tag,
                pcollection,
                coder_details_for_pcollection(pcollection, components),
            )
        })
        .collect();
    entries.sort();
    entries.join(" | ")
}

fn coder_details_for_pcollection(pcollection_id: &str, components: &Components) -> String {
    let Some(pcollection) = components.pcollections.get(pcollection_id) else {
        return "coder: <missing pcollection metadata>".to_string();
    };

    let component_coders = components
        .coders
        .get(&pcollection.coder_id)
        .map(|coder| {
            if coder.component_coder_ids.is_empty() {
                "-".to_string()
            } else {
                coder.component_coder_ids.join(", ")
            }
        })
        .unwrap_or_else(|| "<missing coder metadata>".to_string());

    format!(
        "coder: {}; components: {}",
        pcollection.coder_id, component_coders,
    )
}

fn wrap_html(value: &str, max_line_len: usize) -> String {
    let escaped_segments: Vec<_> = wrap_path(value, max_line_len)
        .into_iter()
        .map(|line| html_escape(&line))
        .collect();

    escaped_segments.join("<BR ALIGN=\"LEFT\"/>")
}

fn wrap_path(value: &str, max_line_len: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();

    for segment in value.split('/') {
        let candidate_len = if current.is_empty() {
            segment.chars().count()
        } else {
            current.chars().count() + 1 + segment.chars().count()
        };

        if !current.is_empty() && candidate_len > max_line_len {
            lines.push(current);
            current = segment.to_string();
        } else if current.is_empty() {
            current = segment.to_string();
        } else {
            current.push('/');
            current.push_str(segment);
        }
    }

    if !current.is_empty() {
        lines.push(current);
    }

    if lines.is_empty() {
        lines.push("-".to_string());
    }

    lines
}

fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}
