use crate::fusion::pipeline::{ConsumerMetaData, ExecutableGraph, ExecutableNode};
use crate::fusion::stage::SplittableStage;
use beam_model_rs::v1::Components;
use petgraph::Graph;
use petgraph::graph::NodeIndex;
use std::{collections::HashMap, fmt};

impl fmt::Debug for ExecutableNode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.debug_label())
    }
}

pub fn executable_graph_to_dot(graph: &ExecutableGraph) -> String {
    let executable_graph = graph.get_executable_graph();

    let mut dot = String::new();
    dot.push_str(&format!(
        "digraph executable_graph {{\n    // Generated by flaredb visualization\n    // nodes: {}\n    // edges: {}\n    rankdir = TB\n    graph [fontname = \"Helvetica\", nodesep = 0.60, ranksep = 0.80]\n    node [fontname = \"Helvetica\", fontsize = 10]\n    edge [fontname = \"Helvetica\", fontsize = 9]\n",
        executable_graph.node_count(),
        executable_graph.edge_count(),
    ));

    // Emit top-level nodes. Splittable nodes are expanded into a cluster
    // containing their nested nodes and edges rather than a summary node.
    for node_index in executable_graph.node_indices() {
        let node = &executable_graph[node_index];
        match node {
            ExecutableNode::Splittable(stage) => {
                write_splittable_cluster(&mut dot, node_index.index(), stage);
            }
            _ => {
                dot.push_str(&format!(
                    "    {} [{}];\n",
                    outer_node_id(node_index.index()),
                    node_attributes(node_index.index(), node),
                ));
            }
        }
    }

    // Emit outer edges, rewiring endpoints that touch a splittable cluster to
    // the concrete inner node that produces/consumes the edge's PCollection.
    for edge_index in executable_graph.edge_indices() {
        let (source, target) = executable_graph
            .edge_endpoints(edge_index)
            .expect("edge endpoints should exist");
        let metadata = executable_graph
            .edge_weight(edge_index)
            .expect("edge weight should exist");

        let source_id = edge_source_id(&executable_graph[source], source.index(), metadata);
        let target_id = edge_target_id(&executable_graph[target], target.index(), metadata);

        dot.push_str(&format!(
            "    {} -> {} [{}];\n",
            source_id,
            target_id,
            edge_attributes(metadata),
        ));
    }

    dot.push_str("}\n");
    dot
}

fn outer_node_id(index: usize) -> String {
    format!("n{}", index)
}

fn cluster_id(index: usize) -> String {
    format!("cluster_{}", index)
}

fn inner_node_id(outer_index: usize, inner_index: usize) -> String {
    format!("cluster_{}_n{}", outer_index, inner_index)
}

fn write_splittable_cluster(dot: &mut String, outer_index: usize, stage: &SplittableStage) {
    dot.push_str(&format!("    subgraph cluster_{} {{\n", outer_index));
    dot.push_str(&format!(
        "        label = <{}>;\n",
        splittable_cluster_label_html(outer_index, stage)
    ));
    dot.push_str("        style = rounded;\n");
    dot.push_str("        color = \"#7c3aed\";\n");
    dot.push_str("        fontcolor = \"#7c3aed\";\n");
    dot.push_str("        labeljust = \"l\";\n");

    let nested = stage.graph();
    for inner_index in nested.node_indices() {
        let node = &nested[inner_index];
        dot.push_str(&format!(
            "        {} [{}];\n",
            inner_node_id(outer_index, inner_index.index()),
            node_attributes(inner_index.index(), node),
        ));
    }

    for edge_index in nested.edge_indices() {
        let (source, target) = nested
            .edge_endpoints(edge_index)
            .expect("nested edge endpoints should exist");
        let metadata = nested
            .edge_weight(edge_index)
            .expect("nested edge weight should exist");

        dot.push_str(&format!(
            "        {} -> {} [{}];\n",
            inner_node_id(outer_index, source.index()),
            inner_node_id(outer_index, target.index()),
            edge_attributes(metadata),
        ));
    }

    dot.push_str("    }\n");
}

fn splittable_cluster_label_html(outer_index: usize, stage: &SplittableStage) -> String {
    let mut output_pcols: Vec<_> = stage.output_pcols().iter().cloned().collect();
    output_pcols.sort();

    let mut rows = vec![
        header_row(&format!("Splittable Run #{}", outer_index), "#c4b5fd"),
        kv_row("id", stage.id()),
        section_row(&format!("boundary outputs ({})", output_pcols.len())),
    ];
    if output_pcols.is_empty() {
        rows.push(value_row("-"));
    } else {
        for output_pcol in output_pcols {
            rows.push(value_row(&output_pcol));
        }
    }

    table_html("#7c3aed", "#f5f3ff", rows)
}

fn edge_source_id(node: &ExecutableNode, node_index: usize, metadata: &ConsumerMetaData) -> String {
    match node {
        ExecutableNode::Splittable(stage) => splittable_producer_id(stage, node_index, metadata),
        _ => outer_node_id(node_index),
    }
}

fn edge_target_id(node: &ExecutableNode, node_index: usize, metadata: &ConsumerMetaData) -> String {
    match node {
        ExecutableNode::Splittable(stage) => splittable_consumer_id(stage, node_index, metadata),
        _ => outer_node_id(node_index),
    }
}

fn splittable_producer_id(
    stage: &SplittableStage,
    outer_index: usize,
    metadata: &ConsumerMetaData,
) -> String {
    find_inner_node(stage.graph(), |node| {
        node.output_pcols()
            .contains(metadata.produced_pcol_id.as_str())
    })
    .map(|inner| inner_node_id(outer_index, inner.index()))
    .unwrap_or_else(|| cluster_id(outer_index))
}

fn splittable_consumer_id(
    stage: &SplittableStage,
    outer_index: usize,
    metadata: &ConsumerMetaData,
) -> String {
    let nested = stage.graph();

    let by_transform = find_inner_node(nested, |node| match node {
        ExecutableNode::Worker(worker) => worker.transforms().iter().any(|transform| {
            transform.node().unique_name.as_str() == metadata.consumer_transfrom_id.as_str()
        }),
        ExecutableNode::Runner(runner) => {
            runner.unique_name().as_str() == metadata.consumer_transfrom_id.as_str()
        }
        ExecutableNode::Splittable(_) => false,
    });

    let by_input = find_inner_node(nested, |node| match node {
        ExecutableNode::Worker(worker) => {
            worker.input_pcol().id.as_str() == metadata.produced_pcol_id.as_str()
        }
        _ => false,
    });

    by_transform
        .or(by_input)
        .map(|inner| inner_node_id(outer_index, inner.index()))
        .unwrap_or_else(|| cluster_id(outer_index))
}

fn find_inner_node<P>(
    graph: &Graph<ExecutableNode, ConsumerMetaData>,
    predicate: P,
) -> Option<NodeIndex>
where
    P: Fn(&ExecutableNode) -> bool,
{
    graph.node_indices().find(|&index| predicate(&graph[index]))
}

fn node_attributes(node_index: usize, node: &ExecutableNode) -> String {
    format!(
        "label = <{}>, shape = plain",
        node_label_html(node_index, node),
    )
}

fn edge_attributes(metadata: &ConsumerMetaData) -> String {
    format!(
        "label = <{}>, color = \"#6b7280\", fontcolor = \"#374151\"",
        edge_label_html(metadata),
    )
}

fn node_label_html(node_index: usize, node: &ExecutableNode) -> String {
    match node {
        ExecutableNode::Worker(stage) => {
            let ordered_transforms: Vec<_> = stage.transforms().into_iter().collect();
            let components = stage.components();

            let mut output_pcols: Vec<_> = stage
                .output_pcols()
                .iter()
                .map(|pcollection| pcollection.id.clone())
                .collect();
            output_pcols.sort();

            let mut rows = vec![
                header_row(&format!("Worker Node #{}", node_index), "#bfdbfe"),
                kv_row("id", &stage.id()),
                kv_row("input", &stage.input_pcol().id),
            ];
            for (index, transform) in ordered_transforms.iter().enumerate() {
                let transform_node = transform.node();
                rows.push(flow_transform_row(index + 1, &transform_node.unique_name));
                rows.push(flow_io_row(
                    "consumes",
                    &format_pcollection_map(&transform_node.inputs, &components),
                ));
                rows.push(flow_io_row(
                    "produces",
                    &format_pcollection_map(&transform_node.outputs, &components),
                ));
            }

            rows.push(section_row(&format!("outputs ({})", output_pcols.len())));
            if output_pcols.is_empty() {
                rows.push(value_row("-"));
            } else {
                for output_pcol in output_pcols {
                    rows.push(value_row(&output_pcol));
                }
            }

            table_html("#2563eb", "#eff6ff", rows)
        }
        ExecutableNode::Runner(transform) => {
            let mut output_pcols: Vec<_> = transform.output_pcol_ids().into_iter().collect();
            output_pcols.sort();

            let mut rows = vec![
                header_row(&format!("Runner Node #{}", node_index), "#fde68a"),
                kv_row("id", &transform.id()),
                kv_row("name", &transform.unique_name()),
                section_row(&format!("outputs ({})", output_pcols.len())),
            ];

            if output_pcols.is_empty() {
                rows.push(value_row("-"));
            } else {
                for output_pcol in output_pcols {
                    rows.push(value_row(&output_pcol));
                }
            }

            table_html("#d97706", "#fffbeb", rows)
        }
        ExecutableNode::Splittable(stage) => {
            let mut output_pcols: Vec<_> = stage.output_pcols().iter().cloned().collect();
            output_pcols.sort();

            let mut rows = vec![
                header_row(&format!("Splittable Node #{}", node_index), "#c4b5fd"),
                kv_row("id", stage.id()),
                kv_row("nested stages", &stage.graph().node_count().to_string()),
                section_row(&format!("boundary outputs ({})", output_pcols.len())),
            ];
            if output_pcols.is_empty() {
                rows.push(value_row("-"));
            } else {
                for output_pcol in output_pcols {
                    rows.push(value_row(&output_pcol));
                }
            }

            table_html("#7c3aed", "#f5f3ff", rows)
        }
    }
}

fn edge_label_html(metadata: &ConsumerMetaData) -> String {
    let component_coders = metadata
        .component_coder
        .as_ref()
        .map(|coders| {
            if coders.is_empty() {
                "-".to_string()
            } else {
                coders.join(", ")
            }
        })
        .unwrap_or_else(|| "-".to_string());

    table_html(
        "#6b7280",
        "#f9fafb",
        vec![
            header_row("PCollection edge", "#e5e7eb"),
            kv_row("producer", &metadata.producer_transform_id),
            kv_row("pcol", &metadata.produced_pcol_id),
            kv_row("coder", &metadata.coder_id),
            kv_row("components", &component_coders),
            kv_row("consumer", &metadata.consumer_transfrom_id),
        ],
    )
}

fn table_html(border_color: &str, background_color: &str, rows: Vec<String>) -> String {
    format!(
        "<TABLE BORDER=\"1\" CELLBORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"5\" COLOR=\"{}\" BGCOLOR=\"{}\">{}</TABLE>",
        border_color,
        background_color,
        rows.join(""),
    )
}

fn header_row(value: &str, background_color: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"CENTER\" BGCOLOR=\"{}\"><B>{}</B></TD></TR>",
        background_color,
        html_escape(value),
    )
}

fn section_row(value: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"LEFT\"><B>{}</B></TD></TR>",
        html_escape(value),
    )
}

fn kv_row(key: &str, value: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"LEFT\"><B>{}:</B> {}</TD></TR>",
        html_escape(key),
        wrap_html(value, 64),
    )
}

fn flow_transform_row(index: usize, value: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"LEFT\" BGCOLOR=\"#dbeafe\"><B>{}. {}</B></TD></TR>",
        index,
        wrap_html(value, 72),
    )
}

fn flow_io_row(key: &str, value: &str) -> String {
    format!(
        "<TR><TD ALIGN=\"LEFT\"><I>{}:</I> {}</TD></TR>",
        html_escape(key),
        wrap_html(value, 84),
    )
}

fn value_row(value: &str) -> String {
    format!("<TR><TD ALIGN=\"LEFT\">{}</TD></TR>", wrap_html(value, 72),)
}

fn format_pcollection_map(values: &HashMap<String, String>, components: &Components) -> String {
    if values.is_empty() {
        return "-".to_string();
    }

    let mut entries: Vec<_> = values
        .iter()
        .map(|(tag, pcollection)| {
            format!(
                "{}: {} ({})",
                tag,
                pcollection,
                coder_details_for_pcollection(pcollection, components),
            )
        })
        .collect();
    entries.sort();
    entries.join(" | ")
}

fn coder_details_for_pcollection(pcollection_id: &str, components: &Components) -> String {
    let Some(pcollection) = components.pcollections.get(pcollection_id) else {
        return "coder: <missing pcollection metadata>".to_string();
    };

    let component_coders = components
        .coders
        .get(&pcollection.coder_id)
        .map(|coder| {
            if coder.component_coder_ids.is_empty() {
                "-".to_string()
            } else {
                coder.component_coder_ids.join(", ")
            }
        })
        .unwrap_or_else(|| "<missing coder metadata>".to_string());

    format!(
        "coder: {}; components: {}",
        pcollection.coder_id, component_coders,
    )
}

fn wrap_html(value: &str, max_line_len: usize) -> String {
    let escaped_segments: Vec<_> = wrap_path(value, max_line_len)
        .into_iter()
        .map(|line| html_escape(&line))
        .collect();

    escaped_segments.join("<BR ALIGN=\"LEFT\"/>")
}

fn wrap_path(value: &str, max_line_len: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();

    for segment in value.split('/') {
        let candidate_len = if current.is_empty() {
            segment.chars().count()
        } else {
            current.chars().count() + 1 + segment.chars().count()
        };

        if !current.is_empty() && candidate_len > max_line_len {
            lines.push(current);
            current = segment.to_string();
        } else if current.is_empty() {
            current = segment.to_string();
        } else {
            current.push('/');
            current.push_str(segment);
        }
    }

    if !current.is_empty() {
        lines.push(current);
    }

    if lines.is_empty() {
        lines.push("-".to_string());
    }

    lines
}

fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}
